#!/usr/bin/env python3
"""Install the final-closure focused forecasts and recompute every consumer.

``audit/final_closure_local_runs.py`` produces, on macOS,

* 20 focused XGBoost runs (original focused search/final-fit protocol, with
  the corrected target-minute feature alignment), and
* one local CPU-mode LSTM run for ``MS_25320`` on the past-only input.

This script

1. verifies every run (``final_closure_local_runs.verify_run``: Darwin
   environment, input/split/trainer hashes, 200/15 complete trials,
   4 effective XGBoost folds with the expected boundaries, 4,320 held-out
   timestamps, artefact hashes);
2. preserves the pre-closure canonical forecast files and training logs once
   under ``experiments/results/superseded_2026-09-28_final_closure/`` and
   writes new canonical ``experiments/results/{xgb,lstm}_forecasts.parquet``
   (XGBoost: all 20 services from the new runs; LSTM: MS_25320 from the local
   run, the other 19 services byte-for-byte semantic copies) and
   ``xgb_training_log.csv`` / ``lstm_training_log.csv`` rows describing the
   runs that produced the canonical models;
3. reruns every producer that reads the focused learned forecasts and splices
   focused rows into mixed-tier files;
4. checks invariants: files outside the declared learned-forecast consumers
   are byte-identical before/after; ARIMA rows and unaffected LSTM rows of the
   focused replay/accuracy tables are unchanged; non-focused statistical
   families are unchanged;
5. independently replays B6/B7 for 20 services x {XGBoost, LSTM} x 3 budgets
   and compares overload counts exactly and costs to rounding;
6. checks that the MS_25320 held-out replays do not depend on the eight
   corrected pre-test minutes.

    python3 audit/recompute_final_closure_downstream.py --write
    python3 audit/recompute_final_closure_downstream.py --check

``--check`` repeats steps 1, 2 (in memory, compared exactly with the
installed canonical parquet files and logs), 5 and 6, and compares the
recorded post-write hashes of all consumer outputs with the current files.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np
import pandas as pd

PAPER = Path(__file__).resolve().parents[1]
RESEARCH = PAPER.parent
EXP = RESEARCH / "experiments"
RESULTS = EXP / "results"
sys.path.insert(0, str(PAPER / "audit"))
import final_closure_local_runs as runs  # noqa: E402

RUNS = runs.DEFAULT_OUT
OUT = RUNS / "downstream"
SUPERSEDED = RESULTS / "superseded_2026-09-28_final_closure"
ROUND2_SUPERSEDED = RESULTS / "superseded_2026-09-28"
ROUND2_SUMMARY = PAPER / "audit/verified_results/focused_causal_refit/downstream/summary.json"
LSTM_SERVICE = "MS_25320"
PAST_ONLY = EXP / "data/service_timeseries_200_verified" / f"{LSTM_SERVICE}.parquet"
HISTORICAL_INPUT = EXP / "data/service_timeseries" / f"{LSTM_SERVICE}.parquet"

# Files that read the focused learned forecasts.
ALLOWED_CHANGES = {
    "experiments/results/xgb_forecasts.parquet",
    "experiments/results/lstm_forecasts.parquet",
    "experiments/results/xgb_training_log.csv",
    "experiments/results/lstm_training_log.csv",
    "experiments/results/advanced_policy_replay_per_service.csv",
    "experiments/results/advanced_policy_replay_summary.csv",
    "experiments/results/advanced_forecasting_comparison.csv",
    "experiments/results/c5_frontier_density.csv",
    "experiments/results/exp2_coverage_calibration.csv",
    "experiments/results/exp3_window_sensitivity.csv",
    "experiments/results/exp_clopper_pearson_ci.csv",
    "experiments/results/exp_statistical_tests.csv",
    "experiments/results/c4_diag_by_model.csv",
    "experiments/results/c4_exchangeability_diagnostics.csv",
    "experiments/results/c1_adaptive_conformal.csv",
    "experiments/results/exp8_cost_decomposition.csv",       # reads learned forecasts (not in manuscript)
    "experiments/reports/forecasting_advanced_report.md",
    "analysis/audit/timeline_results/warmstart_sensitivity_per_service.csv",
    "analysis/audit/timeline_results/warmstart_sensitivity_summary.csv",
    "analysis/audit/timeline_results/timeline_methodology.json",
    "analysis/audit/statistical_results/paired_effect_intervals.csv",
    "analysis/audit/overhead_results/per_service.csv",
    "analysis/audit/overhead_results/stage_totals.csv",
    "analysis/audit/overhead_results/sensitivity_summary.csv",
    "analysis/audit/phase6_results/focused_figure_data.csv",
}
# Regenerated by run_supplemental_experiments.py from persistence inputs only:
# expected byte-identical; any change is reported (not silently accepted).
REGENERATED_EXPECTED_IDENTICAL = {
    "experiments/results/exp4_alpha_sweep.csv",
    "experiments/results/exp5a_guardrail_natural.csv",
    "experiments/results/exp5b_guardrail_shift.csv",
    "experiments/results/exp5c_guardrail_magnitude.csv",
    "experiments/results/exp7_runlength.csv",
    "experiments/results/exp9_penalty_sensitivity.csv",
    "experiments/results/exp10_recovery_time.csv",
}
ALLOWED_PREFIXES = (
    "experiments/figures/",                      # regenerated figure files
    "analysis/figures/verified/fig_focused_",
    "analysis/figures/verified/fig_window_sensitivity_phase6",
    "analysis/figures/exp_c4_exchangeability",
    "experiments/results/superseded_2026-09-28_final_closure/",
)
WATCHED_ROOTS = (
    EXP / "results", EXP / "reports", EXP / "figures", EXP / "data" / "splits",
    PAPER / "audit" / "timeline_results", PAPER / "audit" / "statistical_results",
    PAPER / "audit" / "overhead_results", PAPER / "audit" / "phase6_results",
    PAPER / "audit" / "verified_results", PAPER / "figures",
)
# Input-evidence and other result files whose semantic content must not move.
SEMANTIC_INVARIANTS = (
    "experiments/results/baseline_replay_per_service.csv",
    "experiments/results/risk_policy_replay_per_service.csv",
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def rel(path: Path) -> str:
    return os.path.relpath(path, RESEARCH)


def snapshot() -> dict[str, str]:
    out = {}
    for root in WATCHED_ROOTS:
        for path in sorted(root.rglob("*")):
            if not path.is_file() or path.name == ".DS_Store" or "__pycache__" in path.parts:
                continue
            if RUNS in path.parents:        # the new runs and this script's outputs
                continue
            out[rel(path)] = sha256(path)
    return out


def allowed(name: str) -> bool:
    return name in ALLOWED_CHANGES or name.startswith(ALLOWED_PREFIXES)


# Steps 1-2: runs and canonical forecasts
def verify_runs() -> None:
    services = runs.focused_services()
    bad = [s for s in services if not runs.verify_run("xgb", s)]
    if not runs.verify_run("lstm", LSTM_SERVICE):
        bad.append(f"lstm:{LSTM_SERVICE}")
    if bad:
        raise SystemExit(f"final-closure runs missing or not verified: {bad}")


def run_forecasts(model: str, service: str) -> pd.DataFrame:
    return pd.read_parquet(RUNS / model / service / "forecasts.parquet").sort_values("timestamp")


def pre_closure(name: str) -> Path:
    """The canonical file as it was before this closure step."""
    saved = SUPERSEDED / name
    return saved if saved.exists() else RESULTS / name


def expected_forecasts(model: str) -> pd.DataFrame:
    old = pd.read_parquet(pre_closure(f"{model}_forecasts.parquet"))
    services = runs.focused_services()
    assert sorted(old.msname.unique()) == services and len(old) == 20 * 4320
    replace = services if model == "xgb" else [LSTM_SERVICE]
    parts = [old[~old.msname.isin(replace)]]
    for service in replace:
        fresh = run_forecasts(model, service)
        before = old[old.msname == service].sort_values("timestamp")
        assert np.array_equal(before.timestamp.to_numpy(), fresh.timestamp.to_numpy()), service
        parts.append(fresh[old.columns].astype(old.dtypes.to_dict()))
    new = pd.concat(parts, ignore_index=True)
    new = new.sort_values(["msname", "timestamp"], kind="stable").reset_index(drop=True)
    kept = old[~old.msname.isin(replace)].sort_values(["msname", "timestamp"]).reset_index(drop=True)
    pd.testing.assert_frame_equal(kept, new[~new.msname.isin(replace)].reset_index(drop=True), check_exact=True)
    if model == "lstm" and (ROUND2_SUPERSEDED / "lstm_forecasts.parquet").exists():
        # Project history only: the 19 untouched LSTM services are also identical to the
        # original run. Skipped in a fresh reproduction, where that file does not exist.
        original = pd.read_parquet(ROUND2_SUPERSEDED / "lstm_forecasts.parquet")
        original = original[original.msname != LSTM_SERVICE].sort_values(["msname", "timestamp"]).reset_index(drop=True)
        pd.testing.assert_frame_equal(original, kept, check_exact=True)
    assert new.msname.nunique() == 20 and len(new) == 20 * 4320
    assert new.groupby("msname").timestamp.nunique().eq(4320).all()
    return new


def expected_log(model: str) -> pd.DataFrame:
    old = pd.read_csv(pre_closure(f"{model}_training_log.csv"))
    replace = runs.focused_services() if model == "xgb" else [LSTM_SERVICE]
    rows = []
    for _, row in old.iterrows():
        if row.msname in replace:
            fresh = pd.read_csv(RUNS / model / row.msname / "training_log_row.csv").iloc[0]
            rows.append({c: fresh[c] for c in old.columns})
        else:
            rows.append(row.to_dict())
    return pd.DataFrame(rows, columns=old.columns)


def install(write: bool) -> dict:
    report = {}
    for model in ("xgb", "lstm"):
        fc = expected_forecasts(model)
        lg = expected_log(model)
        canonical_fc = RESULTS / f"{model}_forecasts.parquet"
        canonical_lg = RESULTS / f"{model}_training_log.csv"
        if write:
            SUPERSEDED.mkdir(parents=True, exist_ok=True)
            for src in (canonical_fc, canonical_lg):
                if not (SUPERSEDED / src.name).exists():
                    shutil.copy2(src, SUPERSEDED / src.name)
            fc.to_parquet(canonical_fc, index=False)
            lg.to_csv(canonical_lg, index=False)
        else:
            pd.testing.assert_frame_equal(pd.read_parquet(canonical_fc), fc, check_exact=True)
            # Logs are CSV text.  pandas' default C float parser is not correctly
            # rounded, so the same text can parse to doubles one ulp apart on
            # different platforms; floats are therefore compared to 1e-12
            # (relative), everything else exactly.  Byte identity of the stored
            # log is enforced separately by the post-write hashes and manifest.
            stored = pd.read_csv(canonical_lg)
            fresh = pd.read_csv(io.StringIO(lg.to_csv(index=False)))
            assert list(stored.columns) == list(fresh.columns) and len(stored) == len(fresh), model
            for column in stored.columns:
                if pd.api.types.is_float_dtype(stored[column]):
                    assert np.allclose(stored[column], fresh[column], rtol=1e-12, atol=0, equal_nan=True), column
                else:
                    assert stored[column].astype(str).tolist() == fresh[column].astype(str).tolist(), column
        report[model] = {"services_replaced": 20 if model == "xgb" else 1, "rows": int(len(fc))}
    # The superseded copies must match the canonical hashes recorded in ROUND2_SUMMARY.
    if ROUND2_SUMMARY.exists() and SUPERSEDED.exists():
        r2 = json.loads(ROUND2_SUMMARY.read_text())["canonical_forecasts_sha256"]
        for model in ("xgb", "lstm"):
            assert sha256(SUPERSEDED / f"{model}_forecasts.parquet") == r2[model], model
    return report


# Step 3: producers
def run(cmd: list[str], log: Path) -> None:
    with open(log, "w") as handle:
        proc = subprocess.run(cmd, cwd=RESEARCH, stdout=handle, stderr=subprocess.STDOUT)
    if proc.returncode != 0:
        raise SystemExit(f"command failed ({proc.returncode}): {' '.join(cmd)}; see {log}")


def splice_timeline() -> None:
    target = PAPER / "audit" / "timeline_results"
    saved = {name: pd.read_csv(target / name) for name in (
        "warmstart_sensitivity_per_service.csv", "warmstart_sensitivity_summary.csv")}
    run([sys.executable, str(PAPER / "audit" / "recompute_timeline_sensitivity.py")], OUT / "log_timeline.txt")
    for name, old in saved.items():
        fresh = pd.read_csv(target / name)
        if (fresh.tier != "focused20").any():
            continue
        merged = pd.concat([fresh[fresh.tier == "focused20"], old[old.tier != "focused20"]],
                           ignore_index=True)[old.columns]
        merged.to_csv(target / name, index=False)


def splice_statistics() -> None:
    import statistical_robustness as sr  # noqa: E402
    cwd = os.getcwd()
    os.chdir(RESEARCH)
    sys.path.insert(0, str(EXP / "src"))
    import exp_core  # noqa: E402
    rng = np.random.default_rng(sr.SEED)
    focused = sr.load_focused_frame(EXP, exp_core)
    overload = [
        ("B6 vs B7", "B6", "B7", "overload_fraction", "less"),
        ("B6 vs B8", "B6", "B8", "overload_fraction", "less"),
        ("B6 vs B2", "B6", "B2", "overload_fraction", "less"),
        ("B6 vs B3", "B6", "B3", "overload_fraction", "less"),
        ("B6 vs B4", "B6", "B4", "overload_fraction", "less"),
        ("Persistence vs ARIMA", "B6", "ARIMA", "overload_fraction", "less"),
        ("XGBoost vs ARIMA", "XGB", "ARIMA", "overload_fraction", "less"),
        ("LSTM vs ARIMA", "LSTM", "ARIMA", "overload_fraction", "less"),
        ("LSTM vs XGBoost", "LSTM", "XGB", "overload_fraction", "less"),
    ]
    cost = [
        ("LSTM vs reactive cost", "LSTM", "Reactive", "rel_cost", "less"),
        ("XGBoost vs reactive cost", "XGB", "Reactive", "rel_cost", "less"),
    ]
    rows = sr.paired_effect_rows(focused, overload, "focused_overload", 20_000, rng)
    rows += sr.paired_effect_rows(focused, cost, "focused_cost", 20_000, rng)
    os.chdir(cwd)
    path = PAPER / "audit" / "statistical_results" / "paired_effect_intervals.csv"
    old = pd.read_csv(path)
    merged = pd.concat([pd.DataFrame(rows), old[~old.family.str.startswith("focused")]], ignore_index=True)
    merged[old.columns].to_csv(path, index=False)


def producers() -> None:
    src, audit, py = EXP / "src", PAPER / "audit", sys.executable
    run([py, str(src / "run_advanced_policy_replay.py")], OUT / "log_advanced_policy_replay.txt")
    run([py, str(src / "evaluate_advanced_forecasting.py")], OUT / "log_evaluate_advanced_forecasting.txt")
    run([py, str(src / "run_c5_frontier_density.py")], OUT / "log_c5.txt")
    run([py, str(src / "run_c1_adaptive_conformal.py"), "--fresh"], OUT / "log_c1.txt")
    run([py, str(src / "run_supplemental_experiments.py")], OUT / "log_supplemental.txt")
    run([py, str(src / "run_c4_exchangeability.py")], OUT / "log_c4.txt")
    run([py, "-c", "import sys; sys.path.insert(0, 'experiments/src'); "
         "import exp_validator_fixes as m; m.fix4_statistical_tests()"], OUT / "log_validator_fix4.txt")
    splice_timeline()
    splice_statistics()
    run([py, str(audit / "recompute_overhead_accounting.py"), "--write"], OUT / "log_overhead.txt")
    run([py, str(audit / "plot_phase6_figures.py"), "--write"], OUT / "log_phase6.txt")
    run([py, str(audit / "recompute_arima_causal.py"), "--diagnostic-figure-only"], OUT / "log_c4_figure.txt")


# Step 4: invariants
def semantic_invariants(before_dir: Path) -> dict:
    """Rows that must not depend on the XGBoost/LSTM replacement."""
    out = {}
    a_old = pd.read_csv(before_dir / "advanced_policy_replay_per_service.csv")
    a_new = pd.read_csv(RESULTS / "advanced_policy_replay_per_service.csv")
    keep = lambda f: f[f.policy.str.startswith("arima") | (f.policy.str.startswith("lstm") & (f.msname != LSTM_SERVICE))]  # noqa: E731
    pd.testing.assert_frame_equal(keep(a_old).sort_values(["msname", "policy"]).reset_index(drop=True),
                                  keep(a_new).sort_values(["msname", "policy"]).reset_index(drop=True))
    out["advanced_replay_arima_and_unaffected_lstm_rows_unchanged"] = True
    f_old = pd.read_csv(before_dir / "advanced_forecasting_comparison.csv")
    f_new = pd.read_csv(RESULTS / "advanced_forecasting_comparison.csv")
    keepf = lambda f: f[(f.model == "arima") | ((f.model == "lstm") & (f.msname != LSTM_SERVICE))]  # noqa: E731
    pd.testing.assert_frame_equal(keepf(f_old).sort_values(["msname", "model"]).reset_index(drop=True),
                                  keepf(f_new).sort_values(["msname", "model"]).reset_index(drop=True))
    out["accuracy_arima_and_unaffected_lstm_rows_unchanged"] = True
    s_old = pd.read_csv(before_dir / "paired_effect_intervals.csv")
    s_new = pd.read_csv(PAPER / "audit/statistical_results/paired_effect_intervals.csv")
    nf = lambda f: f[~f.family.str.startswith("focused")].reset_index(drop=True)  # noqa: E731
    pd.testing.assert_frame_equal(nf(s_old), nf(s_new))
    out["non_focused_statistical_families_unchanged"] = True
    return out


# Steps 5-6: replays
def independent_replay() -> dict:
    """Recompute B6/B7 rows from the canonical forecasts and compare with the CSV."""
    cwd = os.getcwd()
    os.chdir(RESEARCH)
    sys.path.insert(0, str(EXP / "src"))
    import run_advanced_policy_replay as adv  # noqa: E402
    from metrics import evaluate_capacity  # noqa: E402
    from risk_policy import RiskPolicyConfig  # noqa: E402
    split = json.loads((EXP / "data/splits/split_definition.json").read_text())
    smap = {s["name"]: s for s in split["splits"]}
    stored = pd.read_csv(RESULTS / "advanced_policy_replay_per_service.csv").set_index(["msname", "policy"])
    baseline = pd.read_csv(RESULTS / "baseline_replay_per_service.csv")
    observed = baseline[baseline.policy == "observed_capacity"].set_index("msname").c_total
    checked, worst = 0, 0.0
    for model in ("xgb", "lstm"):
        fc = pd.read_parquet(RESULTS / f"{model}_forecasts.parquet")
        for service in runs.focused_services():
            frame = pd.read_parquet(EXP / "data/service_timeseries" / f"{service}.parquet").sort_values("timestamp")
            history = pd.concat([adv.split_frame(frame, smap["train"]), adv.split_frame(frame, smap["calibration"])],
                                ignore_index=True)
            test = adv.split_frame(frame, smap["test"])
            demand = test.cpu_sum.to_numpy(float)
            forecast = fc[fc.msname == service].sort_values("timestamp").forecast.to_numpy(float)
            for delta in adv.DELTA_VALUES:
                for guard, label in ((False, "margin_only"), (True, "guardrail")):
                    config = RiskPolicyConfig(delta=delta, window=adv.WINDOW, alpha=adv.ALPHA, mu=adv.MU,
                                              rho=adv.RHO, guardrail_h=adv.GUARDRAIL_H,
                                              guardrail_gamma=adv.GUARDRAIL_GAMMA,
                                              use_margin=True, use_guardrail=guard)
                    capacity = adv.simulate_policy_with_external_forecast(history, test, forecast, config)
                    res = evaluate_capacity(service=service, policy="x", timestamps=test["timestamp"],
                                            demand=demand, capacity=capacity, mu=adv.MU,
                                            cost_config=adv.COST_CONFIG)
                    row = stored.loc[(service, f"{model}_conformal_{label}_d{delta}")]
                    assert int(res["overload_count"]) == int(row.overload_count), (service, model, delta, label)
                    rel_cost = res["c_total"] / observed[service]
                    diff = abs(rel_cost - row.relative_cost_vs_observed)
                    assert np.isclose(rel_cost, row.relative_cost_vs_observed, rtol=1e-9, atol=1e-12)
                    assert np.isclose(res["c_total"], row.c_total, rtol=1e-9, atol=1e-6)
                    worst = max(worst, float(diff))
                    checked += 1
    os.chdir(cwd)
    assert checked == 240, checked
    return {"rows_checked": checked, "overload_counts_exact": True, "max_abs_relative_cost_diff": worst}


def replay_input_invariance() -> dict:
    cwd = os.getcwd()
    os.chdir(RESEARCH)
    sys.path.insert(0, str(EXP / "src"))
    import exp_core  # noqa: E402
    import run_advanced_policy_replay as adv  # noqa: E402
    from risk_policy import RiskPolicyConfig  # noqa: E402
    split = json.loads((EXP / "data/splits/split_definition.json").read_text())
    hist_old, test_old = exp_core.load_service_data(HISTORICAL_INPUT, split)
    hist_new, test_new = exp_core.load_service_data(PAST_ONLY, split)
    pd.testing.assert_frame_equal(test_old.reset_index(drop=True), test_new.reset_index(drop=True))
    out = {}
    for model in ("persistence", "xgb", "lstm"):
        forecast = None
        if model != "persistence":
            frame = pd.read_parquet(RESULTS / f"{model}_forecasts.parquet")
            forecast = frame[frame.msname == LSTM_SERVICE].sort_values("timestamp").forecast.to_numpy(float)
        for delta in (0.10, 0.05, 0.01):
            a = exp_core.simulate_policy(hist_old, test_old, forecast, delta=delta, W=240,
                                         use_margin=True, use_guardrail=True)
            b = exp_core.simulate_policy(hist_new, test_new, forecast, delta=delta, W=240,
                                         use_margin=True, use_guardrail=True)
            out[f"{model}_d{delta}"] = all(np.array_equal(np.asarray(a[k]), np.asarray(b[k]))
                                           for k in a if not isinstance(a[k], dict))
        if model != "persistence":
            for delta in adv.DELTA_VALUES:
                for guard in (False, True):
                    config = RiskPolicyConfig(delta=delta, window=adv.WINDOW, alpha=adv.ALPHA, mu=adv.MU,
                                              rho=adv.RHO, guardrail_h=adv.GUARDRAIL_H,
                                              guardrail_gamma=adv.GUARDRAIL_GAMMA,
                                              use_margin=True, use_guardrail=guard)
                    a = adv.simulate_policy_with_external_forecast(hist_old, test_old, forecast, config)
                    b = adv.simulate_policy_with_external_forecast(hist_new, test_new, forecast, config)
                    out[f"advanced_{model}_d{delta}_guard{guard}"] = bool(np.array_equal(a, b))
    os.chdir(cwd)
    assert all(out.values()), out
    return out


def output_hashes(names) -> dict:
    return {n: sha256(RESEARCH / n) for n in sorted(names) if (RESEARCH / n).exists()}


def _save_before_copies(before_dir: Path) -> None:
    for name in ("advanced_policy_replay_per_service.csv", "advanced_forecasting_comparison.csv"):
        shutil.copy2(RESULTS / name, before_dir / name)
    shutil.copy2(PAPER / "audit/statistical_results/paired_effect_intervals.csv", before_dir / "paired_effect_intervals.csv")
    for name in ("advanced_policy_replay_summary.csv", "exp_statistical_tests.csv", "c5_frontier_density.csv"):
        shutil.copy2(RESULTS / name, before_dir / name)
    for name in ("stage_totals.csv", "per_service.csv", "sensitivity_summary.csv"):
        shutil.copy2(PAPER / "audit/overhead_results" / name, before_dir / f"overhead_{name}")
    shutil.copy2(PAPER / "audit/timeline_results/warmstart_sensitivity_summary.csv", before_dir / "warmstart_sensitivity_summary.csv")



def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    verify_runs()

    if args.check:
        summary = json.loads((OUT / "summary.json").read_text())
        install(write=False)
        stale = {n: d for n, d in summary["post_write_sha256"].items() if sha256(RESEARCH / n) != d}
        if stale:
            raise SystemExit(f"consumer outputs changed since --write: {sorted(stale)}")
        replay = independent_replay()
        invariance = replay_input_invariance()
        print(json.dumps({"runs_verified": 21, "canonical_equals_expected": True,
                          "post_write_hashes_match": len(summary["post_write_sha256"]),
                          "independent_replay": replay, "replay_input_invariance": all(invariance.values())},
                         indent=2))
        return 0

    OUT.mkdir(parents=True, exist_ok=True)
    before_dir = OUT / "before"
    snapshot_file = OUT / "before_snapshot.json"
    if snapshot_file.exists():
        # A previous --write was interrupted after installing: keep the original
        # pre-closure snapshot and copies instead of re-reading modified files.
        before = json.loads(snapshot_file.read_text())
        print("resuming: using the saved pre-closure snapshot")
    else:
        before = snapshot()
        before_dir.mkdir(exist_ok=True)
        _save_before_copies(before_dir)
        snapshot_file.write_text(json.dumps(before, indent=1))
    installed = install(write=True)
    producers()
    after = snapshot()
    changed = sorted(n for n in set(before) | set(after) if before.get(n) != after.get(n))
    regenerated_changed = [n for n in changed if n in REGENERATED_EXPECTED_IDENTICAL]
    if regenerated_changed:
        print(f"WARNING: persistence-only regenerated outputs changed: {regenerated_changed}")
    unexpected = [n for n in changed if not allowed(n) and n not in REGENERATED_EXPECTED_IDENTICAL]
    if unexpected:
        raise SystemExit(f"unexpected changes outside the learned-forecast consumers: {unexpected}")
    for name in SEMANTIC_INVARIANTS:
        assert before[name] == after[name], name
    semantic = semantic_invariants(before_dir)
    replay = independent_replay()
    invariance = replay_input_invariance()
    summary = {
        "installed": installed,
        "run_forecasts_sha256": {f"{m}/{s}": sha256(RUNS / m / s / "forecasts.parquet")
                                 for m in ("xgb", "lstm")
                                 for s in (runs.focused_services() if m == "xgb" else [LSTM_SERVICE])},
        "canonical_forecasts_sha256": {m: sha256(RESULTS / f"{m}_forecasts.parquet") for m in ("xgb", "lstm")},
        "superseded_sha256": {p.name: sha256(p) for p in sorted(SUPERSEDED.iterdir()) if p.is_file()},
        "changed_files": changed,
        "persistence_only_outputs_changed": regenerated_changed,
        "unchanged_watched_files": len(after) - len([n for n in changed if n in after]),
        "semantic_invariants": semantic,
        "independent_replay": replay,
        "replay_input_invariance": invariance,
        "post_write_sha256": output_hashes([n for n in changed if n in after]),
        "timing_policy": (
            "xgb_training_log.csv: all 20 rows from the final-closure runs; lstm_training_log.csv: MS_25320 "
            "row from the local final-closure run, other 19 rows from the original focused run. Earlier logs "
            "are kept in superseded_2026-09-28_final_closure/. The overhead tables therefore describe the "
            "runs that produced the canonical models; corrective reruns are not added as deployment cost."
        ),
    }
    (OUT / "summary.json").write_text(json.dumps(summary, indent=2))
    print(json.dumps({k: summary[k] for k in ("installed", "semantic_invariants", "independent_replay")}, indent=2))
    print(f"{len(changed)} files changed; all within the declared learned-forecast consumers")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
